on:
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: GraphQL Inspector
        uses: kamilkisiela/graphql-inspector@v3.4.0  
        with: 
          schema: schema.graphql
