on:
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: kamilkisiela/graphql-inspector@master
        with: 
          schema: 'schema.graphql'
          endpoint: 'https://c496d6e31894.ngrok.app'