on:
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: install graphql-inspector for ci
        run: npm i --global @graphql-inspector/diff-command
      - name: fetch main schema from hive
        env:
          HIVE_TOKEN: ${{ secrets.HIVE_TOKEN }}
          HIVE_CDN_ENDPOINT: ${{ secrets.HIVE_CDN_ENDPOINT }}
          HIVE_CDN_ACCESSTOKEN: ${{ secrets.HIVE_CDN_ACCESSTOKEN }}
        run: |
          curl -sSL https://graphql-hive.com/install.sh | sh
          hive artifact:fetch --artifact sdl \
            --cdn.endpoint ${{ env.HIVE_CDN_ENDPOINT }} \
            --cdn.accessToken ${{ env.HIVE_CDN_ACCESSTOKEN }} \
            --outputFile=oldschema.graphql

      - name: schema diff
        run: npm run schema:diff
      
      - name: cleanup
        run: rm -rf master-be-schema.graphql
        