name: Trigger CD Workflow

on:
  repository_dispatch:
    types:
      - schema-published
      
jobs:
  trigger:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CD Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-cd